"""
Provenance — Data lineage tagging for every output value.

Every value produced by the system carries a Provenance tag indicating
its origin. This is a mandatory architectural invariant: no output value
may exist without provenance.
"""

from enum import Enum


class Provenance(str, Enum):
    """Data provenance tag — every output value must carry one.

    Rules:
        - REAL: came from live engine telemetry hardware.
        - SIMULATED: generated by the physics simulator.
        - CSV_REPLAY: read from a recorded CSV file.
        - DERIVED: computed by L2 physics derivation from input data.
        - MODEL_OUTPUT: produced by an L3 ML model.
    """

    REAL = "REAL"
    SIMULATED = "SIMULATED"
    CSV_REPLAY = "CSV_REPLAY"
    DERIVED = "DERIVED"
    MODEL_OUTPUT = "MODEL_OUTPUT"


class ChannelValidity(str, Enum):
    """Validity state of an individual telemetry channel.

    A channel can be valid, invalid (with reason), or missing entirely.
    The system must NEVER silently replace stale/invalid values.
    """

    VALID = "VALID"
    INVALID_RANGE = "INVALID_RANGE"          # Outside physical range
    INVALID_RATE = "INVALID_RATE"            # Rate of change too high
    INVALID_STALE = "INVALID_STALE"          # Value hasn't changed (stuck sensor)
    INVALID_DROPOUT = "INVALID_DROPOUT"      # Sensor dropout / missing
    INVALID_INTEGRITY = "INVALID_INTEGRITY"  # Failed integrity check
    MISSING = "MISSING"                      # Channel not present in record


class FlightPhase(str, Enum):
    """Mission flight phase enumeration."""

    GROUND = "GROUND"
    TAKEOFF = "TAKEOFF"
    CLIMB = "CLIMB"
    CRUISE = "CRUISE"
    DESCENT = "DESCENT"
    LANDING = "LANDING"


class FaultClass(int, Enum):
    """Nine-class fault taxonomy for the Rotax 915 iS.

    Class definitions are fixed and must not be changed without updating
    the entire ML pipeline, explanation templates, and training data.
    """

    NOMINAL = 0
    MISFIRE = 1
    DETONATION_KNOCK = 2
    EXHAUST_VALVE_LEAK = 3
    INTAKE_BOOST_LEAK = 4
    OIL_DEGRADATION = 5
    COOLING_FAULT = 6
    BEARING_WEAR = 7
    SENSOR_FAULT = 8


class AlertLevel(str, Enum):
    """Advisory alert severity levels, ordered by increasing severity."""

    NOMINAL = "NOMINAL"
    WATCH = "WATCH"
    CAUTION = "CAUTION"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class DegradationState(str, Enum):
    """Engine degradation state classification."""

    HEALTHY = "HEALTHY"
    WATCH = "WATCH"
    CAUTION = "CAUTION"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class DiagnosticStatus(str, Enum):
    """Diagnostic status for subsystem & cylinder analysis."""

    NORMAL = "NORMAL"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
    INVALID = "INVALID"


class InferenceStatus(str, Enum):
    """Execution status for ML model inference and predictive analytics."""

    SUCCESS = "SUCCESS"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
    INVALID_INPUT = "INVALID_INPUT"
    SCHEMA_MISMATCH = "SCHEMA_MISMATCH"
    INFERENCE_ERROR = "INFERENCE_ERROR"
    INSUFFICIENT_HISTORY = "INSUFFICIENT_HISTORY"
    INVALID_PREDICTION = "INVALID_PREDICTION"


class ModelLifecycleStatus(str, Enum):
    """Lifecycle status for an ML model artifact."""

    UNLOADED = "UNLOADED"
    READY = "READY"
    UNAVAILABLE = "UNAVAILABLE"
    ERROR = "ERROR"


class DeploymentRole(str, Enum):
    """Deployment role boundary enumeration."""

    EDGE = "EDGE"
    GROUND = "GROUND"
    SIMULATION = "SIMULATION"


class CommunicationState(str, Enum):
    """Communication link health status."""

    CONNECTED = "CONNECTED"
    DEGRADED = "DEGRADED"
    DISCONNECTED = "DISCONNECTED"
    BUFFERING = "BUFFERING"
    RECOVERING = "RECOVERING"


class OverflowPolicy(str, Enum):
    """Buffer overflow discard policy."""

    DISCARD_OLDEST = "DISCARD_OLDEST"
    DISCARD_NEWEST = "DISCARD_NEWEST"



